import Navbar from "@components/Navbar";
import Footer from "@components/Footer";
import "./globals.css";
import {unstable_setRequestLocale} from 'next-intl/server';


export const metadata = {
  title: "Smart Tour Dynamic",
  description: "Generated by Medusa Global",
};


const locales = ['en', 'es', 'tr'];


export function generateStaticParams() {
  return locales.map((locale) => ({locale}));
}



export default function RootLayout({ children, params: {locale}}) {
  return (
    <html lang={locale}>
      <body className="flex flex-col justify-start items-center">
        <Navbar />
        <main className="flex flex-col items-center justify-start">
        {children}
        </main>
        <Footer />
        </body>
    </html>
  );
}
